@baseUrl = https://mysdymw1pa.execute-api.eu-central-1.amazonaws.com/prod/
# @baseUrl = https://api.algotools.io/prod/
@address= ABCD123


### Retrieve settings
GET {{baseUrl}}/reward-collection?address={{address}} HTTP/1.1
content-type: application/json

### Update settings
PUT {{baseUrl}}/reward-collection?address={{address}} HTTP/1.1
content-type: application/json

{
  "address": "{{address}}",
  "enable": true,
  "minimumRewardsToCollect": 3
}